name: Deploy to GitHub Pages
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Detect Node project
        id: node
        run: |
          if [ -f package.json ]; then echo "node=true" >> $GITHUB_OUTPUT; else echo "node=false" >> $GITHUB_OUTPUT; fi

      - name: Setup Node
        if: steps.node.outputs.node == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        if: steps.node.outputs.node == 'true'
        run: npm ci

      - name: Build
        if: steps.node.outputs.node == 'true'
        run: npm run build --if-present || true

      - name: Pick output dir
        id: pick
        run: |
          for d in dist build docs public . ; do
            if [ -d "$d" ]; then echo "dir=$d" >> $GITHUB_OUTPUT; exit 0; fi
          done

      - name: SPA fallback (404.html)
        run: |
          DIR="${{ steps.pick.outputs.dir }}"
          if [ -f "$DIR/index.html" ]; then cp "$DIR/index.html" "$DIR/404.html" || true; fi

      - name: Configure Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.pick.outputs.dir }}

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
